### ISSUE TITLE
Search `PageSize` property is `string` instead of `int`

### ISSUE THREAD

**Issue by hognevevle** [notion-dotnet/notion-sdk-net#134]
```
Notion.Client.NotionApiException: body failed validation: body.page_size should be a number or `undefined`, instead was `"50"`.
         at Notion.Client.RestClient.SendAsync(String requestUri, HttpMethod httpMethod, IDictionary`2 queryParams, IDictionary`2 headers, Action`1 attachContent, CancellationToken cancellationToken)
         at Notion.Client.RestClient.PostAsync[T](String uri, Object body, IDictionary`2 queryParams, IDictionary`2 headers, JsonSerializerSettings serializerSettings, CancellationToken cancellationToken)
         at Notion.Client.SearchClient.SearchAsync(SearchParameters parameters)
```

![CleanShot 2021-09-28 at 13 41 10](https://user-images.githubusercontent.com/2721188/135080151-f2cecf31-3301-45b5-9a4b-aee83095c66d.png)

**Comment by KoditkarVedant** [comment]
@hognevevle Thank you for your contribution. I've merged your PR and it is released as part of 1.4.2 release.
