### ISSUE TITLE
Unable to append child blocks

### ISSUE THREAD

**Issue by Kurupapuru** [notion-dotnet/notion-sdk-net#32]
Looks like `IObject.Object` (`ObjectType` enum) writes as number

### Exception: 
`NotionApiException`

### Exception message: 
`body failed validation: body.children[0].object should be `"block"`, instead was `2`.`

### Stack Trace:    
```
at Notion.Client.RestClient.SendAsync(String requestUri, HttpMethod httpMethod, IDictionary`2 queryParams, IDictionary`2 headers, Action`1 attachContent, CancellationToken cancellationToken) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\NotionDotNet.NotionSdkNet\Src\Notion.Client\RestClient\RestClient.cs:line 102
   at Notion.Client.RestClient.PatchAsync[T](String uri, Object body, IDictionary`2 queryParams, IDictionary`2 headers, JsonSerializerSettings serializerSettings, CancellationToken cancellationToken) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\NotionDotNet.NotionSdkNet\Src\Notion.Client\RestClient\RestClient.cs:line 142
   at Notion.Client.BlocksClient.AppendChildrenAsync(String blockId, BlocksAppendChildrenParameters parameters) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\NotionDotNet.NotionSdkNet\Src\Notion.Client\Api\Blocks\BlocksClient.cs:line 48
   at CompanyName.ProjectStructureAutomatization.App.AppendPageRelationsRecursive(String parentId, Page page) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\CompanyName.TasksStructureAutomatization\App.cs:line 120
```

### Serialization Stack Trace:
```
   at Notion.Client.RestClient.SendAsync(String requestUri, HttpMethod httpMethod, IDictionary`2 queryParams, IDictionary`2 headers, Action`1 attachContent, CancellationToken cancellationToken) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\NotionDotNet.NotionSdkNet\Src\Notion.Client\RestClient\RestClient.cs:line 102
   at Notion.Client.RestClient.PatchAsync[T](String uri, Object body, IDictionary`2 queryParams, IDictionary`2 headers, JsonSerializerSettings serializerSettings, CancellationToken cancellationToken) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\NotionDotNet.NotionSdkNet\Src\Notion.Client\RestClient\RestClient.cs:line 142
   at Notion.Client.BlocksClient.AppendChildrenAsync(String blockId, BlocksAppendChildrenParameters parameters) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\NotionDotNet.NotionSdkNet\Src\Notion.Client\Api\Blocks\BlocksClient.cs:line 48
   at CompanyName.ProjectStructureAutomatization.App.AppendPageRelationsRecursive(String parentId, Page page) in F:\AllProjects\CompanyName\ToolsAndAutomatization\TasksStructureAutomatization\CompanyName.TasksStructureAutomatization\App.cs:line 120
```

**Comment by KoditkarVedant** [comment]
@Kurupapuru Is the PR ready for review?
