### ISSUE TITLE
Notion.Client.NotionApiException: Block type copy_indicator is not supported via the API.

### ISSUE THREAD

**Issue by farukcan** [notion-dotnet/notion-sdk-net#359]
**Describe the bug**
Cannot parse duplicated templated who includes copy_indicator type.

```
2023-02-21T20:45:43.515897852Z fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2023-02-21T20:45:43.515952537Z An unhandled exception has occurred while executing the request.
2023-02-21T20:45:43.516079488Z Notion.Client.NotionApiException: Block type copy_indicator is not supported via the API.
2023-02-21T20:45:43.516092031Z at Notion.Client.RestClient.SendAsync(String requestUri, HttpMethod httpMethod, IDictionary`2 queryParams, IDictionary`2 headers, Action`1 attachContent, CancellationToken cancellationToken)
2023-02-21T20:45:43.516188716Z at Notion.Client.RestClient.GetAsync[T](String uri, IDictionary`2 queryParams, IDictionary`2 headers, JsonSerializerSettings serializerSettings, CancellationToken cancellationToken)
2023-02-21T20:45:43.516273016Z at Notion.Client.BlocksClient.RetrieveChildrenAsync(String blockId, BlocksRetrieveChildrenParameters parameters)
```

**Comment by KoditkarVedant** [comment]
Hi @farukcan, would you like to contribute the the library? I will be happy to accept the PR.

**Comment by KoditkarVedant** [comment]
If this was related to template block - this has been deprecated As of March 27, 2023

Feel free to open if this is still relevant or my understanding is incorrect.
